avatar: https://gallery-1303709080.cos.ap-chengdu.myqcloud.com/hexo-blog/head.jpg # ç½‘ç«™ Logo
background: # æ—¢æ˜¯åšå®¢çš„èƒŒæ™¯ï¼Œåˆæ˜¯æ–‡ç« é»˜è®¤å¤´å›¾
  path: https://gallery-1303709080.cos.ap-chengdu.myqcloud.com/hexo-blog/article-bg.jpg
  width: 1440
  height: 480
favicon:
  href: https://gallery-1303709080.cos.ap-chengdu.myqcloud.com/hexo-blog/head.jpg # ç½‘ç«™å›¾æ ‡
  type: image/x-icon # å›¾æ ‡ç±»å‹ï¼Œå¯èƒ½çš„å€¼æœ‰(image/png, image/vnd.microsoft.icon, image/x-icon, image/gif)

function: # åŠŸèƒ½å¼€å…³ï¼Œå¯é€‰å€¼ï¼ˆtrue,falseï¼‰
  globalToc: true # å¼€å¯è¯¥åŠŸèƒ½ä¼šè‡ªåŠ¨å¼€å¯æ–‡ç«  TOCï¼ˆæ–‡ç« ç›®å½•ï¼‰ åŠŸèƒ½
  wordCount: true # æ˜¯å¦å¼€å¯æ–‡ç« å­—æ•°ç»Ÿè®¡ (true, false)

imageCDN: # å›¾ç‰‡ CDN åŠŸèƒ½
  enable: false # å¼€å¯è¯¥åŠŸèƒ½  
  origin: /../../images/ # å›¾ç‰‡åŸå§‹ç›®å½•
  to: https://cdn.jsdelivr.net/gh/nexmoe/nexmoe.github.io@latest/images/ # å›¾ç‰‡ CDN åŸŸå
  
# é™„åŠ å›¾æ ‡åº“ ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/config/icon
iconlib: //at.alicdn.com/t/c/font_3841883_wx2jzr3wdlh.css # //at.alicdn.com/t/font_1038733_0xvrvpg9c0r.css

search: 
  type: engine # å¯é€‰engineï¼ˆç”¨æœç´¢å¼•æ“æœç´¢ï¼‰ã€swiftypeã€æˆ–localï¼ˆæœ¬åœ°æœç´¢ï¼‰
  url: https://cn.bing.com/search?q=site:nexmoe.com # æœç´¢å¼•æ“åœ°å€ï¼Œåœ¨typeä¸ºswiftypeæ—¶æ— æ•ˆ e.g:https://www.google.com/search?q={ä½ çš„åšå®¢é“¾æ¥}
  id: <swiftype-id> # swiftypeçš„idï¼Œè§å¯ç”¨æ•™ç¨‹ã€‚åœ¨typeä¸ºengineæ—¶æ— æ•ˆ

cdn: # è¿™é‡Œå¯ä»¥ä¿®æ”¹ç«™ç‚¹ä½¿ç”¨çš„åº“çš„CDN
  disqusjs: 
    css: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqusjs.min.css
    js: https://cdn.jsdelivr.net/npm/disqusjs@1.2.5/dist/disqus.min.js
  gitalk:
    css: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.css
    js: https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js
  valine:
    js: https://cdn.jsdelivr.net/npm/valine
  waline:
    js: https://cdn.jsdelivr.net/npm/@waline/client/dist/Waline.min.js
  twikoo:
    js: https://cdn.staticfile.org/twikoo/1.6.8/twikoo.all.min.js

menu:
  å›åˆ°é¦–é¡µ: 
    - /
    - icon-home
  æ–‡ç« å½’æ¡£:  # ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/article/archive
    - /system/archive.html
    - icon-container
  å…³äºæˆ‘:
    - /system/about.html
    - icon-info-circle
  ç•™è¨€æ¿:
    - /system/message.html
    - icon-appstore-fill
  å‹äººå¸: 
    - /system/friends.html # ä½¿ç”¨è¯´æ˜ï¼šhttps://docs.nexmoe.com/article/py

widgets:
- search
- social
- category
- tagcloud
#- hitokoto # ä¸€è¨€ widget
# - archive #settings: widgetAchive
# - recent_posts
# - link #settings: widgetLink

maxTagcloud: 0  # æ ‡ç­¾äº‘ç»„ä»¶æ˜¾ç¤ºçš„æ ‡ç­¾æ•°é‡ï¼Œ0 è¡¨ç¤ºä¸é™åˆ¶

social:
  å“”å“©å“”å“©:
    - https://space.bilibili.com/1134123186
    - icon-bilibili
    - rgb(84,191,106)
    - rgba(84,191,106, .15) #- rgb(231, 106, 141)
    #- rgba(231, 106, 141, .15)
  GitHub:
    - https://github.com/2061360308
    - icon-github
    - rgb(84,191,106)
    - rgba(84,191,106, .15) #- rgb(25, 23, 23)
    #- rgba(25, 23, 23, .15)
  Gitee:
    - https://gitee.com/lueyes
    - icon-gitee
    - rgb(84,191,106)
    - rgba(84,191,106, .15) #rgb(206,239,228)
  CSDN:
    - https://blog.csdn.net/m0_70826521
    - icon-csdn
    - rgb(84,191,106)
    - rgba(84,191,106, .15) #rgb(206,239,228)

# è‡ªå®šä¹‰æ ·å¼ï¼Œå¯ç”¨åå¯åœ¨ç«™ç‚¹çš„sourceæ–‡ä»¶å¤¹ä¸‹æ–°å»ºcustom.cssè‡ªå®šä¹‰ç«™ç‚¹æ ·å¼
customstyle: false

# å‘æœç´¢å¼•æ“éªŒè¯ä½ å¯¹ç«™ç‚¹çš„æ‰€æœ‰æƒï¼Œç”¨äºå‘æœç´¢å¼•æ“æäº¤ sitemap å’Œç®¡ç†ç«™ç‚¹è¢«æœç´¢å¼•æ“æ”¶å½•çš„æƒ…å†µã€‚
site_verification: 
  google:
  baidu:

# ç»Ÿè®¡ç³»ç»Ÿï¼Œç›®å‰æ”¯æŒ Google analytics.js ç»Ÿè®¡ã€Google Tag Manager ç»Ÿè®¡ã€CNZZ ç»Ÿè®¡ã€è…¾è®¯ç»Ÿè®¡ã€51.Laç»Ÿè®¡ã€ç™¾åº¦ç»Ÿè®¡
analytics: 
  google_site_id: #<ID>
  gtags_site_id: #<ID>
  cnzz_site_id: #<ID>
  tencent_site_id: #<ID>
  la_site_id: #<ID>
  baidu_site_id: #<ID>
  gtm_container_id: #<ID>

# è¯„è®ºæ¡†ï¼Œç›®å‰æ”¯æŒ gitalk,gitment,valine,disqus,disqusjs,changyan,livere,DiscussBot,waline ä½¿ç”¨ false å¯ä»¥å…³é—­
comment: waline
gitalk:
  admin: nexmoe # æ‹¥æœ‰å¯¹è¯¥repoè¿›è¡Œæ“ä½œçš„ GitHub username
  owner: nexmoe # æŒæœ‰è¯¥ repo çš„ GitHub username
  repo: nexmoe.github.io # å­˜æ”¾è¯„è®ºçš„ issue æ‰€åœ¨çš„ repo
  clientID: 80b2453b6d5f37ad6225 # GitHub Client ID
  clientSecret: 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret
gitment:
  owner: nexmoe # æŒæœ‰è¯¥ repo çš„ GitHub username
  repo: nexmoe.github.io # å­˜æ”¾è¯„è®ºçš„ issue æ‰€åœ¨çš„ repo
  clientID: 80b2453b6d5f37ad6225 # GitHub Client ID
  clientSecret: 43e99fa852795c9a7b3eb924b2558c64b84bbdeb # GitHub Client Secret
valine: 
  appId: 6GSGD2JUSrjs3EPP07HYDZkx-MdYXbMMI # leancloud application app id
  appKey: 36OIc4hWj0KShivONN241mnF # leancloud application app key
disqus:
  shortname: <shortname> # ä½ çš„ Disqus shortname
disqusjs:
  shortname: <shortname> # ä½ çš„ Disqus shortname
  sitename: <sitename> # ä½ ç«™ç‚¹çš„åç§°ï¼Œå°†ä¼šæ˜¾ç¤ºåœ¨ã€Œè¯„è®ºåŸºç¡€æ¨¡å¼ã€çš„ header ä¸­ï¼›è¯¥é…ç½®åº”è¯¥å’Œ Disqus Admin - Settings - General - Website Name ä¸€è‡´
  api: https://disqus.skk.moe/disqus/ # DisqusJS è¯·æ±‚çš„ API Endpointï¼Œé€šå¸¸æƒ…å†µä¸‹ä½ åº”è¯¥é…ç½®ä¸€ä¸ª Disqus API çš„åä»£å¹¶å¡«å…¥åä»£çš„åœ°å€ã€‚ä½ ä¹Ÿå¯ä»¥ç›´æ¥ä½¿ç”¨ DISQUS å®˜æ–¹ API çš„ Endpoint https://disqus.com/api/ï¼Œæˆ–æ˜¯ä½¿ç”¨SukkaWæ­å»ºçš„ Disqus API åä»£ Endpoint https://disqus.skk.moe/disqus/ã€‚
  apikey: <api_key> # DisqusJS å‘ API å‘èµ·è¯·æ±‚æ—¶ä½¿ç”¨çš„ API Keyï¼Œä½ åº”è¯¥åœ¨é…ç½® Disqus Application æ—¶è·å–äº† API Key;DisqusJS æ”¯æŒå¡«å…¥ä¸€ä¸ª åŒ…å«å¤šä¸ª API Key çš„ Arrayï¼Œåœ¨æ¯æ¬¡è¯·æ±‚æ—¶ä¼šéšæœºä½¿ç”¨å…¶ä¸­ä¸€ä¸ªï¼›å¦‚æœä½ åªéœ€è¦å¡«å…¥ä¸€ä¸ª API Keyï¼Œåˆ™å¯ä»¥å¡«å…¥ String æˆ– Arrayã€‚
  admin: <admin> # ä½ çš„ç«™ç‚¹çš„ Disqus Moderator çš„ç”¨æˆ·åï¼ˆä¹Ÿå°±æ˜¯ä½ çš„ç”¨æˆ·åï¼‰ã€‚ä½ å¯ä»¥åœ¨ Disqus - Settings - Account - Username è·å–ä½ çš„ Username
  adminLabel: <adminLabel> # ä½ æƒ³æ˜¾ç¤ºåœ¨ Disqus Moderator Badge ä¸­çš„æ–‡å­—ã€‚è¯¥é…ç½®åº”å’Œ Disqus Admin - Settings - Community - Moderator Badge Text ç›¸åŒ
changyan:
  appid: <APP_ID> # ç•…è¨€çš„ APPID
  conf: <CONF> # ç•…è¨€çš„ CONF
  thread_key_type: path # å¯é€‰ id æˆ– path
livere:
  data_uid: <data_uid> # ä½ çš„æ¥å¿…åŠ› UIDï¼Œå¯ä»¥åœ¨æ¥å¿…åŠ›åå°è·å–
DiscussBot:
  id: <id> # ç«™ç‚¹id
  comments: 5 # å¯èƒ½æ˜¯é™åˆ¶æ¯ä½ç”¨æˆ·å•é¡µé¢è¯„è®ºæœ€å¤šæ¡æ•°ï¼Ÿ
  color: # è¯„è®ºæ¡†ä¸»è‰²è°ƒ
  dislike: 0 # æ˜¾ç¤ºå·®è¯„æŒ‰é’®
  icons: 0 # å›¾æ ‡ä¸»é¢˜
  diff: 0 # æ¯ä½ç”¨æˆ·nameä¸åŒé¢œè‰²
#waline: 
#  appId: 6GSGD2JUSrjs3EPP07HYDZkx-MdYXbMMI # leancloud application app id
#  appKey: 36OIc4hWj0KShivONN241mnF # leancloud application app key
#  masterKey: 6b394xnx35BgSeAtHfxXxR5P # leancloud application master key

copyright: '<strong>ç‰ˆæƒå£°æ˜ï¼š</strong>æœ¬æ–‡é‡‡ç”¨ <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/cn/deed.zh" target="_blank">CC BY-NC-SA 3.0 CN</a> åè®®è¿›è¡Œè®¸å¯'
copyTip: "è‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ã€‚\nå•†ä¸šè½¬è½½è¯·è”ç³»ä½œè€…è·å¾—æˆæƒï¼Œéå•†ä¸šè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚\næ¥æºï¼š%url" # è‡ªå®šä¹‰å¤åˆ¶ç‰ˆæƒæ–‡æ¡ˆ,ä½¿ç”¨ %url ä»£æ›¿å½“å‰é¡µé¢URL, ä¿®æ”¹ä¸ºfalseç¦ç”¨

# achive widget behavior
widgetAchive: #æ–‡ç« å½’æ¡£ç»„ä»¶
  archive_type: 'year' #æŒ‰æœˆå±•ç¤ºè¿˜æ˜¯æŒ‰å¹´å±•ç¤º
  show_count: true  #æ˜¯å¦å±•ç¤ºæ•°é‡

widgetLink: #é“¾æ¥ç»„ä»¶
  - title: <title>
    img : <img_path>
    link : <url>
  - title: <title>
    img : <img_path>
    link : <url>

widgetHitokoto: # ä¸€è¨€ç»„ä»¶
  loading_placeholder: 'ğŸš€ è·å–ä¸­...' # æ­£åœ¨ä¸€è¨€æ—¶çš„å ä½ç¬¦
  loading_error_placeholder: 'ğŸ è·å–å¤±è´¥...' # åŠ è½½ä¸€è¨€å¤±è´¥æ—¶çš„å ä½ç¬¦
  category: # ä¸€è¨€å¥å­ç±»å‹ï¼ˆå¯é€‰ï¼‰ï¼Œä¸é…ç½®çš„è¯éšæœºè·å–ï¼Œè¯¦è§ https://developer.hitokoto.cn/sentence/#%E5%8F%A5%E5%AD%90%E7%B1%BB%E5%9E%8B-%E5%8F%82%E6%95%B0


# è‡ªå®šä¹‰ä¾§è¾¹æ å°¾éƒ¨å†…å®¹
sidebar: ''


#waline:
#  enable: true #æ˜¯å¦å¼€å¯
#  serverURL: https://3oakrq.deta.dev # Waline #æœåŠ¡ç«¯åœ°å€ï¼Œæˆ‘ä»¬è¿™é‡Œå°±æ˜¯ä¸Šé¢éƒ¨ç½²çš„ Vercel åœ°å€
#  placeholder: æœ‰ä»€ä¹ˆæƒ³è¯´çš„å˜›~ï¼ˆæ–‡æ˜å“¦ï¼Œç¬‘ï¼‰ # #è¯„è®ºæ¡†çš„é»˜è®¤æ–‡å­—
#  avatar: mm # å¤´åƒé£æ ¼
#  meta: [nick, mail, link] # è‡ªå®šä¹‰è¯„è®ºæ¡†ä¸Šé¢çš„ä¸‰ä¸ªè¾“å…¥æ¡†çš„å†…å®¹
#  pageSize: 10 # è¯„è®ºæ•°é‡å¤šå°‘æ—¶æ˜¾ç¤ºåˆ†é¡µ
#  lang: en # è¯­è¨€, å¯é€‰å€¼: en, zh-cn
#  # Warning: ä¸è¦åŒæ—¶å¯ç”¨ `waline.visitor` ä»¥åŠ `leancloud_visitors`.
#  visitor: false # æ–‡ç« é˜…è¯»ç»Ÿè®¡
#  comment_count: true # å¦‚æœä¸º false , è¯„è®ºæ•°é‡åªä¼šåœ¨å½“å‰è¯„è®ºé¡µé¢æ˜¾ç¤º, ä¸»é¡µåˆ™ä¸æ˜¾ç¤º
#  requiredFields: [] # è®¾ç½®ç”¨æˆ·è¯„è®ºæ—¶å¿…å¡«çš„ä¿¡æ¯ï¼Œ[nick,mail]: [nick] | [nick, mail]
#  libUrl:  # Set custom library cdn url